//
// AEon's Neon Light
//###################
//

//  Generated by MapShader by LordDaimos
//  http://lorddaimos.railbait.com
//
//  Filename: aeneon186.map
//  Shaders merged: 16
//    textures/aeneon/endset_skybox
//    textures/aeneon/ae_zzztrb_b
//    textures/aeneon/ae_zzztpink_jp
//    textures/aeneon/ae_zzztrb_f
//    textures/aeneon/ae_zzztpink_f
//    textures/aeneon/ae_zzztrb_f2
//    textures/aeneon/ae_zzztpink_f2
//    textures/aeneon/ae_zzztrb
//    textures/aeneon/ae_zzztpink
//    textures/aeneon/ae_zzztrb_2
//    textures/aeneon/ae_zzztpink_2
//    textures/aeneon/ae_zzztpred
//    textures/aeneon/ae_zzztblue
//    textures/aeneon/ae_zzztbluet
//    textures/aeneon/ae_zzztredt
//    textures/aeneon/dsiglass

// AEon - Added finer subdivisions: q3map_lightsubdivide 32 was 64

textures/aeneon/endset_skybox
{
	qer_editorimage textures/aeneon/skybox1.tga
	surfaceparm noimpact
	surfaceparm nolightmap
	q3map_globaltexture
	q3map_lightsubdivide 256
	q3map_surfacelight 100
	surfaceparm sky
	q3map_sun 1.0 1.0 1.0 100 105 35
	skyparms env/aeneon/endset - -
}

textures/aeneon/ae_zzztblu_b2
{
	qer_editorimage textures/aeneon/ae_zzztblu_b2.tga
	qer_trans 0.5
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 250	// Was 1000 to brite/opaque
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks		// AEon - weapons should not leave marks
	surfaceparm trans
	cull none				// AEon - See inside, doubles briteness!
	{
		map textures/aeneon/ae_zzztblu_b2.tga	// AEon - 75% brightness reduced
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztpink_jp
{
	qer_editorimage textures/sfx/proto_zzztpink.tga
	qer_trans 0.5
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 4000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks		// AEon - weapons should not leave marks
	surfaceparm trans
	polygonOffset			// AEon	- lets you place the shader flush to the floor.
	nopicmip				// AEon - avoid low poly version
	{
		map textures/sfx/proto_zzztpink.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
		rgbGen wave sin 0 1 0 1 
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztrb_f
{
	qer_editorimage textures/sfx/proto_zzztblu.tga
	qer_trans 0.5
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 1000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks		// AEon - weapons should not leave marks
	surfaceparm trans
	polygonOffset			// AEon	- lets you place the shader flush to the floor.
	nopicmip				// AEon - avoid low poly version
	// cull disable			// AEon - we do not want to see both sides
	{
		map textures/sfx/proto_zzztblu.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE		// AEon == blendfunc add 
	}
}

textures/aeneon/ae_zzztpink_f
{
	qer_editorimage textures/sfx/proto_zzztpink.tga
	qer_trans 0.5
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 1000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks		// AEon - weapons should not leave marks
	surfaceparm trans
	polygonOffset			// AEon	- lets you place the shader flush to the floor.
	nopicmip				// AEon - avoid low poly version
	// cull disable			// AEon - we do not want to see both sides
	{
		map textures/sfx/proto_zzztpink.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztrb_f2
{
	qer_editorimage textures/sfx/proto_zzztblu.tga
	qer_trans 0.5
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 1000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks		// AEon - weapons should not leave marks
	surfaceparm trans
//	polygonOffset			// AEon	- lets you place the shader flush to the floor.
//	nopicmip				// AEon - avoid low poly version
	// cull disable			// AEon - we do not want to see both sides
	{
		map textures/sfx/proto_zzztblu.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE		// AEon == blendfunc add 
	}
}

textures/aeneon/ae_zzztpink_f2
{
	qer_editorimage textures/sfx/proto_zzztpink.tga
	qer_trans 0.5
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 1000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm nomarks		// AEon - weapons should not leave marks
	surfaceparm trans
//	polygonOffset			// AEon	- lets you place the shader flush to the floor.
//	nopicmip				// AEon - avoid low poly version
	// cull disable			// AEon - we do not want to see both sides
	{
		map textures/sfx/proto_zzztpink.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztrb
{
	qer_editorimage textures/sfx/proto_zzztblu.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 2000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzztblu.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztpink
{
	qer_editorimage textures/sfx/proto_zzztpink.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 2000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzztpink.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztrb_2
{
	qer_editorimage textures/sfx/proto_zzztblu.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 200
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzztblu.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztpink_2
{
	qer_editorimage textures/sfx/proto_zzztpink.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 200
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzztpink.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztpred
{
	qer_editorimage textures/sfx/proto_zzzt.tga
	q3map_lightimage textures/aeneon/ae_red_pastel.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 2000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzzt.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztblue
{
	qer_editorimage textures/sfx/proto_zzztblu3.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 2000
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzztblu3.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztbluet
{
	qer_editorimage textures/sfx/proto_zzztblu3.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 500
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzztblu3.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/ae_zzztredt
{
	qer_editorimage textures/sfx/proto_zzzt.tga
	q3map_backsplash 0 0	// Avoid point source lighting on face
	q3map_surfacelight 500
	q3map_lightsubdivide 32	// Finer subdivision
	surfaceparm nolightmap
	surfaceparm nonsolid
	surfaceparm trans
	{
		map textures/sfx/proto_zzzt.tga
		tcGen environment
        tcMod turb 0 0.1 0 0.1
        tcmod scroll .1 .1
		blendfunc GL_ONE GL_ONE
	}
}

textures/aeneon/dsiglass
{
	qer_editorimage textures/aeneon/dsiglass.tga	        
	qer_trans 100.15        
	q3map_surfacelight 250		// AEon - Windows emit light
	surfaceparm nolightmap	
	surfaceparm trans	
	cull disable		
	{			
		map textures/aeneon/dsitinfx.tga				
		blendfunc blend				
		//rgbGen identity				
		tcGen environment
           qer_trans 1.15        
		alphagen const 0.40		// Defines window transparency
	}
}
