// Quake III Arena MD3 control file, generated by MilkShape 3D
//
$model "models/model.md3"
// reference frame
//$frames -1 -1
// frame 1-16
$frames 1 16
$flags 0
$numskins 0

// you can have one or no parent tag

// tags

// meshes (surfaces)
$mesh "rubber_hands"
$skin "models/skin.tga"
$flags 0

$mesh "armor_sides"
$skin "models/skin.tga"
$flags 0

$mesh "covenant_carbine_rubber"
$skin "models/skin.tga"
$flags 0

$mesh "meter"
$skin "models/skin.tga"
$flags 0

