Attribute VB_Name = "lngEnglish"
'
' English language module
'

Public Sub LoadLang_English()
    
    ' common things
    Str_Com_WindowCaption = "DPM Wizard"
    Str_Com_Exit = "&Exit"
    Str_Com_Options = "&Options"
    Str_Com_Next = "&Next >>"
    Str_Com_Prev = "<< &Prev"
    Str_Com_PrevBig = "<< &Prev (discard changes)"
    Str_Com_About = "&About"
    Str_Com_SaveProject = "&Save project"
    Str_Com_GenerateScript = "&Generate script"
    Str_Com_Finish = "&Finish >>"
    
    ' frmWizard
    Str_Wiz_Caption = "Welcome to DPM Wizard"
    Str_Wiz_PathNew = "&Compile new model"
    Str_Wiz_PathContinueLast = "C&ontinue last compilation"
    Str_Wiz_PathBuildLast = "&Build last model"
    Str_Wiz_Open = "&Open saved compilation project"
    Str_Wiz_Preview = "&View existing model with DPM Viewer"
    
    ' frmAbout
    Str_About_Caption = "About DPM Wizard v0.5"
    Str_About_CreatedBy = "Created by"
    Str_About_Created = "Pavel P. [VorteX] Timofeyev" & Str_Nl & "RazorWind Games"
    Str_About_IncludeUtils = "Includes util"
    Str_About_Include = "dpmodel (Ñ) Forest [LordHavoc] Hale" & Str_Nl & "dpmview (Ñ) Forest [LordHavoc] Hale" & Str_Nl & "md52dpm (Ñ) [Riot]" & Str_Nl & "7zip (Ñ) Igor Pavlov" & Str_Nl & "ImageMagick converter © ImageMagick Studio LLC"
    Str_About_VersionHistory = "Version history"
    Str_About_VersionHistoryTxt = "Version 0.5..." & Str_Nl & "    initial build"
    Str_About_Message = "If you like this utility, or want to get new features/source code of it " & Str_Nl & "drop me e-mail to paul.vortex@gmail.com"
    Str_About_Ok = "Oki-doki..."
    
    ' frmOptions
    Str_WizOptions_Caption = "General options"
    Str_WizOptions_InfoOptions = "Path names"
    Str_WizOptions_NewProjectName = "New project name"
    Str_WizOptions_BuildPool = "Build pool dir"
    Str_WizOptions_OpenedProjects = "Opened projects dir"
    Str_WizOptions_SaveLastBuild = "Save last build to"
    Str_WizOptions_Language = "Interface language"
    Str_WizOptions_ArchivesDir = "Archives dir"
    Str_WizOptions_ArchivesExt = "Archives extension"
    Str_WizOptions_Pk3Prefix = "Pk3 archives prefix"
    Str_WizOptions_Pk3Ext = "Pk3 archives extension"
    Str_WizOptions_ModelPathPrefix = "Model path prefix"
    Str_WizOptions_InfoUtils = "Tools/Other"
    Str_WizOptions_DPModelPath = "DPModel"
    Str_WizOptions_MD52DPMPath = "MD5toDPM"
    Str_WizOptions_DPMViewPath = "DPM Viewer"
    Str_WizOptions_ImgConvert = "Texture converter"
    Str_WizOptions_7zPath = "7Z Archiver"
    Str_WizOptions_Notes = "Note: all paths must be relative"
    Str_WizOptions_ResetToDefaults = "Reset to defaults"
    Str_WizOptions_OK = "OK"
    Str_WizOptions_Apply = "Apply"
    Str_WizOptions_Cancel = "Cancel"
    Str_WizOptionsMsgBox = "Are you sure?"
    Str_WizOptionsMsgBox_Caption = "Reset all config to default values"
    
    ' frmOpen, frmOpenProgress
    Str_WizOpen_Caption = "Open existing project"
    Str_WizOpen_Info = "Select file to open"
    Str_WizOpen_Open = "&Open >>"
    Str_WizOpenProg_Caption = "Please wait"
    Str_WizOpenProg_SubCaption = "opening"
    Str_WizOpenProg_Cancel = "Press [Escape] to cancel"
    
    ' frmPreview
    Str_WizPreview_Info = "Select .DPM to view"
        
    ' frmWizardCreate
    Str_WizCreate_Caption = "Select type of compilation"
    Str_WizCreate_Option1 = "Build DPM from HalfLife 1/2 SMD models"
    Str_WizCreate_Option2 = "Convert Doom 3 MD5 To DPM"
    
    ' frmWizardSMD
    Str_WizSMD_Caption = "Build DPM from Half-Life 1/2 SMD files"
    Str_WizSMD_InfoSource = "Path containing source SMD models"
    Str_WizSMD_InfoAnimList1 = "Model animation list"
    Str_WizSMD_InfoAnimList2 = "First file is mesh, others"
    Str_WizSMD_InfoAnimList3 = "are animations"
    
    ' frmWizardSMDbuild
    Str_WizSMDbuild_Caption = "Set output DPM model options and build flags"
    Str_WizSMDbuild_InfoAnimList = "Animations list"
    Str_WizSMDbuild_InfoTextureList = "Textures list"
    Str_WizSMDbuild_InfoModel = "Model information (always use \ for paths, not /)"
    Str_WizSMDbuild_InfoFlags = "Build flags"
    Str_WizSMDbuild_ModelName = "Name"
    Str_WizSMDbuild_ModelPath = "Path"
    Str_WizSMDbuild_ModelOffset = "Offset"
    Str_WizSMDbuild_ModelRotate = "Rotate"
    Str_WizSMDbuild_ModelScale = "Scale"
    Str_WizSMDbuild_InfoModelName = "model will be saved as [thisname].dpm"
    Str_WizSMDbuild_InfoModelPath = "always prefixed by models\"
    Str_WizSMDbuild_InfoModelOffset = "offset model coordinates by this vector"
    Str_WizSMDbuild_InfoModelRotate = "rotation model around vertical axis"
    Str_WizSMDbuild_InfoModelScale = "scale model by this value (1 = no scale)"
    Str_WizSMDbuild_FlagAddSources = "Place sources with builded model"
    Str_WizSMDbuild_FlagViewOutput = "View SMD->DPM converter output"
    Str_WizSMDbuild_SaveProject = "Save project archive for future rebuilds"
    Str_WizSMDbuild_MakePk3 = "Create Pk3 for output model and all it's files"
    Str_WizSMDbuild_MakePk3Name = "Name"
    Str_WizSMDbuild_MakePk3Compression = "Compression"
    
    ' frmWizardSMDbuildDPM
    Str_WizSMDbuildDPM_Caption = "DPM build progress"
    Str_WizSMDbuildDPM_PreviewModel = "&Preview model"
    Str_WizSMDbuildDPM_Rebuild = "&Rebuild"
    Str_WizSMDbuildDPM_StopBuild = "&Stop build"
    Str_WizSMDbuildDPM_OpenBuildDir = "&Open build dir"
    Str_WizSMDbuildDPM_MainMenu = "&Main menu"
    Str_WizSMDbuildDPM_Init = "Initializing..."
    Str_WizSMDbuildDPM_InitError = "Fatal error: build folder is already in use, check for another copy of DPMWizard running or any processes using this dir, build cannot proceed until build dir will become free."
    Str_WizSMDbuildDPM_CheckTools = "Check nesessary tools..."
    Str_WizSMDbuildDPM_CopySrcFiles = "Copy source files..."
    Str_WizSMDbuildDPM_CopyTextures = "Copy textures..."
    Str_WizSMDbuildDPM_CopyTextureLayers = "Copy per-pixel texture layers (norm, gloss, glow etc.)..."
    Str_WizSMDbuildDPM_CopyTexturesError = "Error: file not found"
    Str_WizSMDbuildDPM_CreateSkin = "Create .skin file..."
    Str_WizSMDbuildDPM_Created = "created"
    Str_WizSMDbuildDPM_SaveProject = "Save compilation project..."
    Str_WizSMDbuildDPM_Saved = "saved"
    Str_WizSMDbuildDPM_GenScript = "Generate dpmodel build script..."
    Str_WizSMDbuildDPM_Building = "Building..."
    Str_WizSMDbuildDPM_BatchWritten = "batch written to"
    Str_WizSMDbuildDPM_BatchExecuted = "batch executed."
    Str_WizSMDbuildDPM_BuildingInProgress = "building in progress..."
    Str_WizSMDbuildDPM_BuildComplete = "Build complete:"
    Str_WizSMDbuildDPM_Path = "path is"
    Str_WizSMDbuildDPM_ModelPath = "model path is"
    Str_WizSMDbuildDPM_CreatePk3 = "Creating .pk3 archive..."
    Str_WizSMDbuildDPM_UsingPrefix = "using prefix"
    Str_WizSMDbuildDPM_UsingCompression = "using compression"
    Str_WizSMDbuildDPM_Create7ZFileConfMsgbox = "File with such name already exists in archives folder, do you want to overwrite old file with new?"
    Str_WizSMDbuildDPM_Create7ZFileConfMsgboxCap = "File name conflict"
    Str_WizSMDbuildDPM_Create7ZFileConfNewName = "Enter new name for archive " & Chr(13) & Chr(10) & " " & Chr(13) & Chr(10) & " Filename cannot contain this characters: \ / : *, ? '' < > |" & Chr(13) & Chr(10) & " " & Chr(13) & Chr(10) & "By default program select nearest free name to use"
    Str_WizSMDbuildDPM_Create7ZFileConfNewNameCap = "New name of archive"
    Str_WizSMDbuildDPM_Create7ZFileConfNameError = "You have entered an invalid name, try again"
    Str_WizSMDbuildDPM_Create7ZFileConfNameErrorCap = "Error"

    
    ' clsBuild module
    Str_clsBuild_Tab = "    "
    Str_clsBuild_Warning = "Warning"
    Str_clsBuild_RunTimeError = "Runtime error"
    Str_clsBuild_DelDirTreeErr = " DelDirTree: "
    Str_clsBuild_DelDirTreeErr1 = " DelDirTree: cannot delete root path"
    Str_clsBuild_StartBuildProc = "Start build process"
    Str_clsBuild_ShutdownBuild = "Shutdown."
    Str_clsBuild_StopBuild = "Build stopped."
    Str_clsBuild_BasePath = "base path is"
    Str_clsBuild_UseDir = "use dir"
    Str_clsBuild_UsePathError1 = "Error: Cannot use dir"
    Str_clsBuild_UsePathError2 = "for building."
    Str_clsBuild_UsePathReason = "Reason: runtime error"
    Str_clsBuild_CreatePath = "create path"
    Str_clsBuild_CreatePathError = "Error: Cannot create path"
    Str_clsBuild_Check = "check"
    Str_clsBuild_CheckError = "Error: nesessary file not found."
    Str_clsBuild_CheckNotFound = "not found."
    Str_clsBuild_CheckFound = "found."
    Str_clsBuild_CheckRuntimeError = "Error: runtime error"
    Str_clsBuild_AddFile = "addfile"
    Str_clsBuild_AddDone = "done."
    Str_clsBuild_AddNotFound = "not found."
    Str_clsBuild_AddError = "Error: failed adding required file."
    Str_clsBuild_AddWarning1 = "warning: runtime error"
    Str_clsBuild_AddWarning2 = "warning: failed to copy file to destination"
    Str_clsBuild_AddReason = "reason: runtime error"
End Sub
