Attribute VB_Name = "lngRussian"
'
' Russian language module
'

Public Sub LoadLang_Russian()
    ' generic strings
    Str_Com_WindowCaption = "Мастер DPM"
    Str_Com_Exit = "&Выход"
    Str_Com_Options = "Настр&ойки"
    Str_Com_Next = "&Далее >>"
    Str_Com_Prev = "<< &Назад"
    Str_Com_PrevBig = "&Назад (отмена изменений)"
    Str_Com_About = "&О программе"
    Str_Com_SaveProject = "&Сохранить проект"
    Str_Com_GenerateScript = "&Превью скрипта"
    Str_Com_Finish = "&Закончить >>"
    
     ' frmWizard
    Str_Wiz_Caption = "Мастер DPM приветствует вас"
    Str_Wiz_PathNew = "&Новая сборка"
    Str_Wiz_PathContinueLast = "&Продолжить предыдущую сборку"
    Str_Wiz_PathBuildLast = "Запустить предыдущую сборку"
    Str_Wiz_Open = "&Открыть проект сборки"
    Str_Wiz_Preview = "О&ткрыть модель в просмотрщике DPM"
    
    ' frmAbout
    Str_About_Caption = "О программе Мастер DPM версия 0.5"
    Str_About_CreatedBy = "Автор"
    Str_About_Created = "Павел П. [VorteX] Тимофеев" & Str_Nl & "RazorWind Games"
    Str_About_IncludeUtils = "Включает в себя cвободно распространяемые утилиты"
    Str_About_Include = "dpmodel (С) Forest [LordHavoc] Hale" & Str_Nl & "dpmview (С) Forest [LordHavoc] Hale" & Str_Nl & "md52dpm (С) [Riot]" & Str_Nl & "7zip (С) Игорь Павлов" & Str_Nl & "ImageMagick converter © ImageMagick Studio LLC"
    Str_About_VersionHistory = "История версий"
    Str_About_VersionHistoryTxt = "Версия 0.5..." & Str_Nl & "    начальная сборка"
    Str_About_Message = "Если вам понравилась эта утилита или вы хотите получить её исходники " & Str_Nl & "киньте мне e-mail на paul.vortex@gmail.com" & Str_Nl & "C улыбкой, VorteX"
    Str_About_Ok = "Оки-доки..."
    
    ' frmOptions
    Str_WizOptions_Caption = "Настройки программы"
    Str_WizOptions_InfoOptions = "Имена папок и файлов"
    Str_WizOptions_NewProjectName = "Имя файла нового проекта"
    Str_WizOptions_BuildPool = "Папка сборки"
    Str_WizOptions_OpenedProjects = "Папка открытия"
    Str_WizOptions_SaveLastBuild = "Файл последнего билда"
    Str_WizOptions_Language = "Язык интерфейса"
    Str_WizOptions_ArchivesDir = "Папка архивов"
    Str_WizOptions_ArchivesExt = "Расширение архивов"
    Str_WizOptions_Pk3Prefix = "Префикс Pk3-архивов"
    Str_WizOptions_Pk3Ext = "Расширение Pk3-архивов"
    Str_WizOptions_ModelPathPrefix = "Префикс пути моделей"
    Str_WizOptions_InfoUtils = "Инструментарий/Разное"
    Str_WizOptions_DPModelPath = "DPModel"
    Str_WizOptions_MD52DPMPath = "MD5toDPM"
    Str_WizOptions_DPMViewPath = "DPM Viewer"
    Str_WizOptions_7zPath = "Архиватор 7Z"
    Str_WizOptions_ImgConvert = "Конвертер текстур"
    Str_WizOptions_Notes = "Заметки: все пути к файлам относительные"
    Str_WizOptions_ResetToDefaults = "Сбр. настроек"
    Str_WizOptions_OK = "OK"
    Str_WizOptions_Apply = "Применить"
    Str_WizOptions_Cancel = "Отмена"
    Str_WizOptionsMsgBox = "Вы уверены?"
    Str_WizOptionsMsgBox_Caption = "Сброс настроек на значения по умолчанию"
    
    ' frmOpen, frmOpenProgress
    Str_WizOpen_Caption = "Открытие проекта сборки"
    Str_WizOpen_Info = "Выберите файл проекта"
    Str_WizOpen_Open = "&Открыть >>"
    Str_WizOpenProg_Caption = "Пожалуйста подождите"
    Str_WizOpenProg_SubCaption = "открытие"
    Str_WizOpenProg_Cancel = "Нажмите [Escape] для отмены"
    
    ' frmPreview
    Str_WizPreview_Info = "Выберите модель .DPM, которую собираетесь посмотреть"

    ' frmWizardCreate
    Str_WizCreate_Caption = "Выберите тип сборки"
    Str_WizCreate_Option1 = "Сделать DPM на базе моделей Half-Life1/2 SMD"
    Str_WizCreate_Option2 = "Конвертировать Doom 3 MD5 в DPM"
    
    ' frmWizardSMD
    Str_WizSMD_Caption = "Сделать DPM на базе моделей Half-Life1/2 SMD"
    Str_WizSMD_InfoSource = "Путь с исходными SMD-сценами"
    Str_WizSMD_InfoAnimList1 = "Список сцен"
    Str_WizSMD_InfoAnimList2 = "Первый файл это меш"
    Str_WizSMD_InfoAnimList3 = "остальные - анимация "
    
    ' frmWizardSMDbuild
    Str_WizSMDbuild_Caption = "Опции модели и различные настройки"
    Str_WizSMDbuild_InfoAnimList = "Список сцен"
    Str_WizSMDbuild_InfoTextureList = "Список текстур"
    Str_WizSMDbuild_InfoModel = "Опции модели (всегда используйте \ в путях)"
    Str_WizSMDbuild_InfoFlags = "Разное"
    Str_WizSMDbuild_ModelName = "Имя"
    Str_WizSMDbuild_ModelPath = "Путь"
    Str_WizSMDbuild_ModelOffset = "Смещ."
    Str_WizSMDbuild_ModelRotate = "Пов."
    Str_WizSMDbuild_ModelScale = "Масш."
    Str_WizSMDbuild_InfoModelName = "сохранить полученное как [это].dpm"
    Str_WizSMDbuild_InfoModelPath = "всегда содержит models\ в начале"
    Str_WizSMDbuild_InfoModelOffset = "смещение координат модели"
    Str_WizSMDbuild_InfoModelRotate = "горизонтальный поворот (градусы)"
    Str_WizSMDbuild_InfoModelScale = "масштабировать модель (1 = обычный масштаб)"
    Str_WizSMDbuild_FlagAddSources = "Сохранить исходники вместе с моделью"
    Str_WizSMDbuild_FlagViewOutput = "Посмотреть результаты конвертации SMD->DPM"
    Str_WizSMDbuild_SaveProject = "Сохранить проект в архиве для будущей пересборки"
    Str_WizSMDbuild_MakePk3 = "Создать .Pk3-файл с моделью"
    Str_WizSMDbuild_MakePk3Name = "Имя"
    Str_WizSMDbuild_MakePk3Compression = "Компрессия"
    
    ' frmWizardSMDbuildDPM
    Str_WizSMDbuildDPM_Caption = "Сборка DPM"
    Str_WizSMDbuildDPM_PreviewModel = "&Превью модели"
    Str_WizSMDbuildDPM_Rebuild = "&Пересобрать"
    Str_WizSMDbuildDPM_StopBuild = "&Останов"
    Str_WizSMDbuildDPM_OpenBuildDir = "&Открыть папку сборки"
    Str_WizSMDbuildDPM_MainMenu = "&Главное меню"
    Str_WizSMDbuildDPM_Init = "Инициализация..."
    Str_WizSMDbuildDPM_InitError = "Критическая ошибка: папка сборки занята. Проверьте, не запущена ли утилиты дважды и не работают ли с папкой другие процессы."
    Str_WizSMDbuildDPM_CheckTools = "Проверка необходимых утилит..."
    Str_WizSMDbuildDPM_CopySrcFiles = "Копирование исходных файлов..."
    Str_WizSMDbuildDPM_CopyTextures = "Копирование текстур..."
    Str_WizSMDbuildDPM_CopyTextureLayers = "Копирование дополнительных текстур (norm, gloss, glow и т.д.)..."
    Str_WizSMDbuildDPM_CopyTexturesError = "Ошибка: файл не найден"
    Str_WizSMDbuildDPM_CreateSkin = "Создание .skin-скрипта.."
    Str_WizSMDbuildDPM_Created = "создан"
    Str_WizSMDbuildDPM_SaveProject = "Сохранение проекта сборки..."
    Str_WizSMDbuildDPM_Saved = "сохранен"
    Str_WizSMDbuildDPM_GenScript = "Создание скрипта сборки..."
    Str_WizSMDbuildDPM_Building = "Сборка..."
    Str_WizSMDbuildDPM_BatchWritten = "bat-скрипт сохранен в"
    Str_WizSMDbuildDPM_BatchExecuted = "bat-скрипт запущен."
    Str_WizSMDbuildDPM_BuildingInProgress = "сборка запущена..."
    Str_WizSMDbuildDPM_BuildComplete = "Сборка завершена:"
    Str_WizSMDbuildDPM_Path = "путь "
    Str_WizSMDbuildDPM_ModelPath = "путь к модели"
    Str_WizSMDbuildDPM_CreatePk3 = "Создание .pk3-файла..."
    Str_WizSMDbuildDPM_UsingPrefix = "префикс"
    Str_WizSMDbuildDPM_UsingCompression = "компрессия"
    Str_WizSMDbuildDPM_Create7ZFileConfMsgbox = "Файл с таким именем уже существует, вы хотите перезаписать новый файл поверх него?"
    Str_WizSMDbuildDPM_Create7ZFileConfMsgboxCap = "Конфликт имен файлов"
    Str_WizSMDbuildDPM_Create7ZFileConfNewName = "Введите имя архивного файла " & Chr(13) & Chr(10) & " " & Chr(13) & Chr(10) & " Имя файла не может содержать следующие символы: \ / : *, ? '' < > |" & Chr(13) & Chr(10) & " " & Chr(13) & Chr(10) & "По умолчанию программа выбирает ближайшее свободное имя файла"
    Str_WizSMDbuildDPM_Create7ZFileConfNewNameCap = "Новое имя архивного файла"
    Str_WizSMDbuildDPM_Create7ZFileConfNameError = "Вы ввели неверное имя, попробуйте еще"
    Str_WizSMDbuildDPM_Create7ZFileConfNameErrorCap = "Ошибка"

    ' clsBuild module
    Str_clsBuild_Tab = "    "
    Str_clsBuild_Warning = "Внимание"
    Str_clsBuild_RunTimeError = "Ошибка программы"
    Str_clsBuild_DelDirTreeErr = " DelDirTree: "
    Str_clsBuild_DelDirTreeErr1 = " DelDirTree: невозможно удалить корневую папку"
    Str_clsBuild_StartBuildProc = "Старт процесса сборки"
    Str_clsBuild_ShutdownBuild = "Останов."
    Str_clsBuild_StopBuild = "Сборка отменена."
    Str_clsBuild_BasePath = "базовый путь"
    Str_clsBuild_UseDir = "путь сборки"
    Str_clsBuild_UsePathError1 = "Ошибка: невозможно получить доступ к пути сборки"
    Str_clsBuild_UsePathError2 = "."
    Str_clsBuild_UsePathReason = "Причина: ошибка программы"
    Str_clsBuild_CreatePath = "создать путь"
    Str_clsBuild_CreatePathError = "Ошибка: невозможно создать путь"
    Str_clsBuild_Check = "проверка"
    Str_clsBuild_CheckError = "Ошибка: nнеобходимый файл не найден."
    Str_clsBuild_CheckNotFound = "не найден."
    Str_clsBuild_CheckFound = "найден."
    Str_clsBuild_CheckRuntimeError = "Ошибка: ошибка программы"
    Str_clsBuild_AddFile = "файл"
    Str_clsBuild_AddDone = "завершено."
    Str_clsBuild_AddNotFound = "не найден."
    Str_clsBuild_AddError = "Ошибка: невозможно добавить необходимый файл."
    Str_clsBuild_AddWarning1 = "внимание: ошибка программы"
    Str_clsBuild_AddWarning2 = "внимание: невозможно скопировать файл в конечный путь"
    Str_clsBuild_AddReason = "причина: ошибка программы"
End Sub
