Attribute VB_Name = "MainModule"
' Action
Public Const dpgActionCreate = 1
Public Const dpgActionContinue = 2
Public Const dpgActionRebuild = 3
Public Const dpgActionOpen = 4
Public Const dpgActionView = 5

' Format
Public Const dpgFormatSMD = 1
Public Const dpgFormatMD5 = 2

' BuildPk3, SaveIni, GenerateScriptTxt, RemoveH
Public Const dpgFlagNo = 0
Public Const dpgFlagYes = 1

Const CurrentProjectVersion = 1

' Compilation info
Public Compilation_Version As Integer ' ini file version
Public Compilation_IniFile As String ' ini file name
Public Compilation_Action As Integer ' dpgAction*
Public Compilation_Format As Integer ' dpgFormat*
Public Compilation_BuilkPk3 As Integer
Public Compilation_BuilkPk3_Name As String
Public Compilation_BuilkPk3_Compression As Integer
Public Compilation_AddSourcesToBuild As Integer
Public Compilation_ViewConverterOutput As Integer
Public Compilation_SaveProject As Integer
Public Compilation_ScriptAnimPath As String
Public Compilation_ScriptAnimlistCount As Integer
Public Compilation_ScriptAnimlist(512) As String
Public Compilation_ScriptModelPath As String
Public Compilation_ScriptModelName As String
Public Compilation_ScriptModelOfs(3) As Single
Public Compilation_ScriptModelRotate As Single
Public Compilation_ScriptModelScale As Single

' currently it's temp
Public Compilation_ModelSkins(64) As String
Public Compilation_NumModelSkins As Integer

' default program options
Const ProgramDef_Action = 1
Const ProgramDef_NewBuildIni = "build.dpmwiz"
Const ProgramDef_LastBuildIni = "lastbuild.dpmwiz"
Const ProgramDef_ToolPathSMD2DPM = "tools\dpmodel.exe"
Const ProgramDef_ToolPathMD52DPM = "tools\md52dpm.exe"
Const ProgramDef_ToolPathDPMView = "tools\dpmview.exe"
Const ProgramDef_ToolPath7Z = "tools\7za.exe"
Const ProgramDef_Language = "English"
Const ProgramDef_Buildpath = "build"
Const ProgramDef_Openpath = "opened"
Const ProgramDef_Archivepath = "archive"
Const ProgramDef_ArchiveExt = ".dpmwiza"
Const ProgramDef_ModelsDir = "models\"
Const ProgramDef_Pk3Prefix = "mdl-"
Const ProgramDef_Pk3Extension = ".pk3"
Const ProgramDef_ToolImgConvert = "tools\convert.exe"


' program options
Public Program_Action As Integer
Public Program_NewBuildIni As String
Public Program_LastBuildIni As String
Public Program_ToolPathSMD2DPM As String
Public Program_ToolPathMD52DPM As String
Public Program_ToolPathDPMView As String
Public Program_ToolPath7Z As String
Public Program_Language As String
Public Program_Buildpath As String
Public Program_Openpath As String
Public Program_Archivepath As String
Public Program_ArchiveExt As String
Public Program_ModelsDir As String
Public Program_Pk3Prefix As String
Public Program_Pk3Extension As String
Public Program_ToolImgConvert As String

' opening projects
Public Const OpenProj_No = 0
Public Const OpenProj_Opening = 1
Public OpenProj_State As Integer
Public OpenProj_Path As String
Public OpenProj_File As String

' Stuff
'

Public Sub SwitchForm(tCurrent As Form, tNew As Form)
    tCurrent.Hide
    tNew.Show
End Sub

' string to int conversion
Public Function StrToSingle(tStr As String) As Single
    Dim tVar As Variant
    
    On Error GoTo Error
     
    If (IsNull(tStr) Or tStr = "") Then
        StrToSingle = 0
        Exit Function
    End If
    
    tVar = tStr
    StrToSingle = tVar
Quit:
    Exit Function
Error:
    StrToSingle = 0
    Resume Quit
End Function

Public Function StrToInteger(tStr As String) As Integer
    Dim tVar As Variant
    
    On Error GoTo Error
    
    If (IsNull(tStr) Or tStr = "") Then
        StrToInteger = 0
        Exit Function
    End If
    
    tVar = tStr
    StrToInteger = tVar
    StrToInteger = Fix(StrToInteger)
Quit:
    Exit Function
Error:
    StrToInteger = 0
    Resume Quit
End Function

'
' Compilation
'

Public Function BuildSMDScript(tComments As Boolean, Optional tOverrideOutput As String) As String
    Dim tScript As String
    Dim tNl As String
    Dim tPos As Integer
    
    ' main options
    tNl = Chr(13) & Chr(10)
    tScript = "# This script is generated by DPMWizard " & tNl
    If (tOverrideOutput <> "") Then
        tScript = tScript & "outputdir " & tOverrideOutput & tNl
    Else
        tScript = tScript & "outputdir ." & tNl
    End If
    tScript = tScript & "model " & FileName_MergePaths(Compilation_ScriptModelPath, Compilation_ScriptModelName) & tNl
    tScript = tScript & "origin " & Compilation_ScriptModelOfs(0) & " " & Compilation_ScriptModelOfs(1) & " " & Compilation_ScriptModelOfs(2) & tNl
    tScript = tScript & "rotate " & Compilation_ScriptModelRotate & tNl
    tScript = tScript & "scale " & Compilation_ScriptModelScale & tNl
    
    ' scenes
    tPos = 0
    Do While (tPos < Compilation_ScriptAnimlistCount)
        tScript = tScript & "scene " & Compilation_ScriptAnimlist(tPos) & tNl
        tPos = tPos + 1
    Loop
    BuildSMDScript = tScript
End Function

Public Function ProjectClear()
    Compilation_Action = dpgActionCreate
    Compilation_Format = dpgFormatSMD
    Compilation_BuilkPk3 = dpgFlagNo
    Compilation_BuilkPk3_Name = "unnamed"
    Compilation_BuilkPk3_Compression = 0
    Compilation_SaveProject = dpgFlagNo
    Compilation_ViewConverterOutput = dpgFlagNo
    Compilation_AddSourcesToBuild = dpgFlagNo

    Compilation_ScriptAnimPath = App.path
    Compilation_ScriptAnimlistCount = 0
    Compilation_ScriptModelName = "newmodel"
    Compilation_ScriptModelPath = "models\"
    Compilation_ScriptModelOfs(0) = 0
    Compilation_ScriptModelOfs(1) = 0
    Compilation_ScriptModelOfs(2) = 0
    Compilation_ScriptModelOfs(1) = 0
    Compilation_ScriptModelOfs(2) = 0
    Compilation_ScriptModelRotate = 0
    Compilation_ScriptModelScale = 1
End Function

Public Function ProjectCheckIni(tIniPath As String) As Boolean
    Dim tIni As New clsINI
    If (Dir(tIniPath) = "") Then GoTo Quit_False
    
    tIni.File = tIniPath
    If (StrToInteger(tIni.Read("Generic", "Version")) <> CurrentProjectVersion) Then GoTo Quit_False
    ProjectCheckIni = True
Quit:
    Exit Function
Quit_False:
    ProjectCheckIni = False
    Exit Function
Error:
    ProjectCheckIni = False
    Resume Quit
End Function

Public Function ProjectSaveIni()
    Dim tIni As clsINI
    Set tIni = New clsINI
    Dim tPos As Integer
    
    If (Compilation_IniFile = "") Then Exit Function
    
    If (Dir(Compilation_IniFile) <> "") Then
        Kill Compilation_IniFile
    End If
    tIni.File = Compilation_IniFile
    
    ' Write generic info
    tIni.Add "Generic", "Version", Str(CurrentProjectVersion)
    tIni.Add "Generic", "Action", Str(Compilation_Action)
    tIni.Add "Generic", "Format", Str(Compilation_Format)
    tIni.Add "Generic", "BuildPK3", Str(Compilation_BuilkPk3)
    tIni.Add "Generic", "BuildPK3_Name", Compilation_BuilkPk3_Name
    tIni.Add "Generic", "BuildPK3_Compress", Str(Compilation_BuilkPk3_Compression)
    tIni.Add "Generic", "RemoveHeader", Str(Compilation_RemoveH)
    tIni.Add "Generic", "SaveProjectInArchives", Str(Compilation_SaveProject)
    tIni.Add "Generic", "ViewConverterOutput", Str(Compilation_ViewConverterOutput)
    tIni.Add "Generic", "AddSourcesToBuild", Str(Compilation_AddSourcesToBuild)
    
      
    ' Write SMD animations
    tPos = 0
    tIni.Add "SMDtoDPM", "NumScenes", Str(Compilation_ScriptAnimlistCount)
    tIni.Add "SMDtoDPM", "FilesPath", Compilation_ScriptAnimPath
    Do While (tPos < Compilation_ScriptAnimlistCount)
        tIni.Add "SMDtoDPM", "Scene" & tPos, Compilation_ScriptAnimlist(tPos)
    ' Write MODEL options
        tPos = tPos + 1
    Loop
    
    ' Write MODEL options
    tIni.Add "SMDtoDPM", "ModelName", Compilation_ScriptModelName
    tIni.Add "SMDtoDPM", "ModelPath", Compilation_ScriptModelPath
    tIni.Add "SMDtoDPM", "ModelOfsX", Str(Compilation_ScriptModelOfs(0))
    tIni.Add "SMDtoDPM", "ModelOfsY", Str(Compilation_ScriptModelOfs(1))
    tIni.Add "SMDtoDPM", "ModelOfsZ", Str(Compilation_ScriptModelOfs(2))
    tIni.Add "SMDtoDPM", "ModelRotate", Str(Compilation_ScriptModelRotate)
    tIni.Add "SMDtoDPM", "ModelScale", Str(Compilation_ScriptModelScale)
End Function

Public Function ProjectLoadIni()
    Dim tIni As clsINI
    Set tIni = New clsINI
    Dim tPos As Integer
    
    tIni.File = Compilation_IniFile
    
    ' read generic settings
    Compilation_Action = StrToInteger(tIni.Read("Generic", "Action"))
    Compilation_Format = StrToInteger(tIni.Read("Generic", "Format"))
    Compilation_BuilkPk3 = StrToInteger(tIni.Read("Generic", "BuildPk3"))
    Compilation_BuilkPk3_Name = tIni.Read("Generic", "BuildPK3_Name")
    Compilation_BuilkPk3_Compression = StrToInteger(tIni.Read("Generic", "BuildPK3_Compress"))
    Compilation_SaveProject = StrToInteger(tIni.Read("Generic", "SaveProjectInArchives"))
    Compilation_ViewConverterOutput = StrToInteger(tIni.Read("Generic", "ViewConverterOutput"))
    Compilation_AddSourcesToBuild = StrToInteger(tIni.Read("Generic", "AddSourcesToBuild"))
    
    ' read SMD animations
    Compilation_ScriptAnimlistCount = StrToInteger(tIni.Read("SMDtoDPM", "NumScenes"))
    Compilation_ScriptAnimPath = tIni.Read("SMDtoDPM", "FilesPath")
    tPos = 0
    Do While (tPos < Compilation_ScriptAnimlistCount)
        Compilation_ScriptAnimlist(tPos) = tIni.Read("SMDtoDPM", "Scene" & tPos)
        tPos = tPos + 1
    Loop
    
    ' read SMD model options
    Compilation_ScriptModelName = tIni.Read("SMDtoDPM", "ModelName")
    Compilation_ScriptModelPath = tIni.Read("SMDtoDPM", "ModelPath")
    Compilation_ScriptModelOfs(0) = StrToSingle(tIni.Read("SMDtoDPM", "ModelOfsX"))
    Compilation_ScriptModelOfs(1) = StrToSingle(tIni.Read("SMDtoDPM", "ModelOfsY"))
    Compilation_ScriptModelOfs(2) = StrToSingle(tIni.Read("SMDtoDPM", "ModelOfsZ"))
    Compilation_ScriptModelRotate = StrToSingle(tIni.Read("SMDtoDPM", "ModelRotate"))
    Compilation_ScriptModelScale = StrToSingle(tIni.Read("SMDtoDPM", "ModelScale"))
End Function

'
' Program config
'

Public Sub FlushAppConfig()
    If (Dir(App.path & "\dpmwizard.ini") <> "") Then Kill App.path & "\dpmwizard.ini"
    Call LoadAppConfig
End Sub

Public Sub LoadAppConfig()
    Dim tIni As clsINI
    Set tIni = New clsINI
    Dim tPos As Integer
    
    ' check if file exists, if not - save default ini
    If (Dir(App.path & "\dpmwizard.ini") = "") Then
        tIni.File = App.path & "\dpmwizard.ini"
        tIni.Add "Config", "Action", ProgramDef_Action
        tIni.Add "Config", "NewBuildIni", ProgramDef_NewBuildIni
        tIni.Add "Config", "LastBuildIni", ProgramDef_LastBuildIni
        tIni.Add "Config", "SMD2DPM", ProgramDef_ToolPathSMD2DPM
        tIni.Add "Config", "MD52DPM", ProgramDef_ToolPathMD52DPM
        tIni.Add "Config", "DPMVIEW", ProgramDef_ToolPathDPMView
        tIni.Add "Config", "7Z", ProgramDef_ToolPath7Z
        tIni.Add "Config", "BuildPath", ProgramDef_Buildpath
        tIni.Add "Config", "Language", ProgramDef_Language
        tIni.Add "Config", "OpenPath", ProgramDef_Openpath
        tIni.Add "Config", "ArchivePath", ProgramDef_Archivepath
        tIni.Add "Config", "ArchiveExt", ProgramDef_ArchiveExt
        tIni.Add "Config", "ModelPathPrefix", ProgramDef_ModelsDir
        tIni.Add "Config", "Pk3Prefix", ProgramDef_Pk3Prefix
        tIni.Add "Config", "Pk3Ext", ProgramDef_Pk3Extension
        tIni.Add "Config", "IMAGEMAGICK", ProgramDef_ToolImgConvert
    End If
    
    tIni.File = App.path & "\dpmwizard.ini"
    Program_Action = StrToInteger(tIni.Read("Config", "Action"))
    Program_NewBuildIni = tIni.Read("Config", "NewBuildIni")
    Program_LastBuildIni = tIni.Read("Config", "LastBuildIni")
    Program_ToolPathSMD2DPM = tIni.Read("Config", "SMD2DPM")
    Program_ToolPathMD52DPM = tIni.Read("Config", "MD52DPM")
    Program_ToolPathDPMView = tIni.Read("Config", "DPMVIEW")
    Program_ToolPath7Z = tIni.Read("Config", "7Z")
    Program_Buildpath = tIni.Read("Config", "BuildPath")
    Program_Language = tIni.Read("Config", "Language")
    Program_Openpath = tIni.Read("Config", "OpenPath")
    Program_Archivepath = tIni.Read("Config", "ArchivePath")
    Program_ArchiveExt = tIni.Read("Config", "ArchiveExt")
    Program_ModelsDir = tIni.Read("Config", "ModelPathPrefix")
    Program_Pk3Prefix = tIni.Read("Config", "Pk3Prefix")
    Program_Pk3Extension = tIni.Read("Config", "Pk3Ext")
    Program_ToolImgConvert = tIni.Read("Config", "IMAGEMAGICK")
    
    ' load languages
    LoadLanguages
End Sub

Public Sub SaveAppConfig()
    Dim tIni As clsINI
    Set tIni = New clsINI
    Dim tPos As Integer
    
    If (Dir(App.path & "\dpmwizard.ini") <> "") Then Kill App.path & "\dpmwizard.ini"
    tIni.File = App.path & "\dpmwizard.ini"
    tIni.Add "Config", "Action", Str(Program_Action)
    tIni.Add "Config", "NewBuildIni", Program_NewBuildIni
    tIni.Add "Config", "LastBuildIni", Program_LastBuildIni
    tIni.Add "Config", "SMD2DPM", Program_ToolPathSMD2DPM
    tIni.Add "Config", "MD52DPM", Program_ToolPathMD52DPM
    tIni.Add "Config", "DPMVIEW", Program_ToolPathDPMView
    tIni.Add "Config", "7Z", Program_ToolPath7Z
    tIni.Add "Config", "BuildPath", Program_Buildpath
    tIni.Add "Config", "Language", Program_Language
    tIni.Add "Config", "OpenPath", Program_Openpath
    tIni.Add "Config", "ArchivePath", Program_Archivepath
    tIni.Add "Config", "ArchiveExt", Program_ArchiveExt
    tIni.Add "Config", "ModelPathPrefix", Program_ModelsDir
    tIni.Add "Config", "Pk3Prefix", Program_Pk3Prefix
    tIni.Add "Config", "Pk3Ext", Program_Pk3Extension
    tIni.Add "Config", "IMAGEMAGICK", Program_ToolImgConvert
End Sub

'
' Utils
'

' dele directory and all it's subdirectories
Public Function DelDirTree(dirName As String) As Boolean
    Dim curDirectory As String, fileName As String
    Dim stopFlag As Boolean
    On Error GoTo ErrMsg
    stopFlag = False
    If Right(dirName, 1) = "\" Then
        dirName = Left(dirName, Len(dirName) - 1)
        'ѕровер€ем, не €вл€етс€ ли заданный каталог корневым.
        If Right(dirName, 1) = ":" Then
            MsgBox Str_clsBuild_DelDirTreeErr1, vbInformation, Str_clsBuild_Warning
            stopFlag = True
        End If
    End If
    If Not stopFlag Then
        'ѕровер€ем, существует ли заданный каталог.
        If Len(Dir(dirName, vbDirectory)) <> 0 Then
            If (GetAttr(dirName) And vbReadOnly) <> 0 Then
                SetAttr dirName, vbNormal
            End If
            'ѕровер€ем, не €вл€етс€ ли заданный каталог
            'или один из его подкаталогов текущим.
            '≈сли €вл€етс€, то текущим делаем надкаталог
            'заданного дл€ удалени€ каталога.
            Do
                curDirectory = CurDir
                If InStr(1, curDirectory, dirName, vbTextCompare) > 0 Then
                    ChDir ".."
                Else
                    stopFlag = True
                End If
            Loop While stopFlag = False
            '”дал€ем все файлы в заданном каталоге
            '(или в одном из его подкаталогов).
            fileName = Dir(dirName & "\*.*")
            Do While fileName <> ""
                If (GetAttr(dirName & "\" & fileName) And vbReadOnly) <> 0 Then
                    SetAttr dirName & "\" & fileName, vbNormal
                End If
                Kill dirName & "\" & fileName
                fileName = Dir
            Loop
            'ѕровер€ем наличие подкаталогов.
            Do
                fileName = Dir(dirName & "\*.*", vbDirectory)
                'ѕропускаем "." и ".."
                Do While fileName = "." Or fileName = ".."
                    fileName = Dir
                Loop
                '≈сли подкаталогов нет, то выходим из цикла,
                'иначе снова вызываем функцию DelTree
                '(уже дл€ удалени€ подкаталога).
                If fileName = "" Then
                    Exit Do
                Else
                    If Not DelDirTree(dirName & "\" & fileName) Then
                        GoTo Out
                    End If
                End If
            Loop
            '”дал€ем заданный каталог
            '(или один из его подкаталогов).
            RmDir dirName
            DelDirTree = True
            Exit Function
        End If
    End If
    
Out:
    DelDirTree = False
    Exit Function
ErrMsg:
    MsgBox Str_clsBuild_DelDirTreeErr & Err.Description, vbInformation, Str_clsBuild_RunTimeError
    Resume Out
End Function

'
' create file tree
'
Private Sub CreateDirTree_Recursion(ByVal tModelPath As String)
    Dim tNewPath As String
    On Error GoTo Error
    
    tNewPath = FileName_GetPath(tModelPath)
    If (Right(tNewPath, 1) = "\") Then tNewPath = Mid(tNewPath, 1, Len(tNewPath) - 1)
    If (tNewPath <> "") Then Call CreateDirTree_Recursion(tNewPath)
    MkDir tModelPath
Quit:
    Exit Sub
Error:
    Resume Quit
End Sub
Public Sub CreateDirTree(ByVal tModelPath As String)
    If Right(tModelPath, 1) = "\" Then tModelPath = Mid(tModelPath, 1, Len(tModelPath) - 1)
    If (tModelPath = "") Then Exit Sub
    Call CreateDirTree_Recursion(tModelPath)
End Sub
